Neolution.OrchardCoreModules.PageViewStats/ViewModels/DashboardViewModel.cs
namespace Neolution.OrchardCoreModules.PageViewStats.ViewModels;

using System.Collections.Generic;
using Neolution.OrchardCoreModules.PageViewStats.Models;

public class DashboardViewModel
{
    public int History { get; set; }
    public IList<DailyArchive> PageViewsByDay { get; set; }
    public List<PageViewsPerContentItem> PageViewsByContentItem { get; set; }
}

Neolution.OrchardCoreModules.PageViewStats/Controllers/DashboardController.cs
namespace Neolution.OrchardCoreModules.PageViewStats.Controllers;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Neolution.OrchardCoreModules.PageViewStats.Models;
using Neolution.OrchardCoreModules.PageViewStats.Services;
using Neolution.OrchardCoreModules.PageViewStats.ViewModels;
using OrchardCore.Admin;
using OrchardCore.Autoroute.Models;
using OrchardCore.ContentManagement;
using OrchardCore.Data;
using OrchardCore.Settings;
using YesSql;

[Admin]
public class DashboardController : Controller
{
    private readonly ISession session;
    private readonly IDbConnectionAccessor dbConnectionAccessor;
    private readonly IAuthorizationService authorizationService;
    private readonly IContentManager contentManager;
    private readonly ISiteService siteService;
    private readonly IPageViewsRepository repository;

    private ISqlDialect dialect;
    private string table;

    public DashboardController(ISession session, IDbConnectionAccessor dbConnectionAccessor, IAuthorizationService authorizationService, IContentManager contentManager, ISiteService siteService, IPageViewsRepository repository)
    {
        this.session = session;
        this.dbConnectionAccessor = dbConnectionAccessor;
        this.authorizationService = authorizationService;
        this.contentManager = contentManager;
        this.siteService = siteService;
        this.repository = repository;

        SetupDatabaseFields();
    }

    [HttpGet]
    public async Task<ActionResult> Index(int history)
    {
        if (!await this.authorizationService.AuthorizeAsync(User, PageViewStatsPermissions.ViewPageViewStats))
        {
            return Forbid();
        }

        var settings = await this.siteService.GetSiteSettingsAsync();
        var tz = TimeZoneInfo.FindSystemTimeZoneById(settings.TimeZoneId);
        var now = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, tz);
        var today = DateOnly.FromDateTime(now);

        IList<DailyArchive> pageViews;
        if (history == 0)
        {
            pageViews = await this.repository.LoadAllPageViewsAsync();
        }
        else
        {
            if (history > 30 || history <= 1)
            {
                // Limit history to maximum number of 30 days
                history = 30;
            }

            pageViews = await this.repository.LoadPageViewsAsync(today.AddDays(history * -1), today);
        }

        var contentItems = await this.contentManager.GetAsync(pageViews.SelectMany(x => x.PageViews).Select(x => x.ContentItemId));
        var contentItemList = contentItems.ToList();
        var pageViewsPerSite = new List<PageViewsPerContentItem>();
        foreach (var groupedItems in pageViews.SelectMany(x => x.PageViews).GroupBy(x => x.ContentItemId))
        {
            var pageView = contentItemList.FirstOrDefault(x => x.ContentItemId == groupedItems.Key);
            if (pageView == null)
            {
                continue;
            }

            var item = new PageViewsPerContentItem
            {
                ContentItemId = groupedItems.Key,
                DisplayText = pageView.DisplayText,
                Route = pageView.Get<AutoroutePart>("AutoroutePart"),
                BotViews = groupedItems.Sum(g => g.BotViews),
                UniqueVisitors = groupedItems.Sum(g => g.UniqueVisitors),
                TotalViews = groupedItems.Sum(g => g.TotalViews),
            };

            pageViewsPerSite.Add(item);
        }


        var viewModel = new DashboardViewModel
        {
            History = history,
            PageViewsByDay = pageViews,
            PageViewsByContentItem = pageViewsPerSite
        };

        return View(viewModel);
    }

    private void SetupDatabaseFields()
    {
        dialect = session.Store.Configuration.SqlDialect;

        var tablePrefix = session.Store.Configuration.TablePrefix;
        if (!string.IsNullOrEmpty(tablePrefix))
        {
            tablePrefix += '_';
        }

        table = $"{tablePrefix}{PageView.TableName}";
    }
}

Neolution.OrchardCoreModules.PageViewStats/Controllers/DayController.cs
namespace Neolution.OrchardCoreModules.PageViewStats.Controllers;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Neolution.OrchardCoreModules.PageViewStats.Queries;
using Neolution.OrchardCoreModules.PageViewStats.ViewModels;
using OrchardCore.Admin;
using OrchardCore.Autoroute.Models;
using OrchardCore.ContentManagement;

[Admin]
public class DayController : Controller
{
    private readonly IAuthorizationService authorizationService;
    private readonly IContentManager contentManager;
    private readonly ISender sender;
    
    public DayController(IAuthorizationService authorizationService, IContentManager contentManager, ISender sender)
    {
        this.authorizationService = authorizationService;
        this.contentManager = contentManager;
        this.sender = sender;
    }

    [HttpGet]
    public async Task<ActionResult> Index(DateTime day)
    {
        if (!await this.authorizationService.AuthorizeAsync(User, PageViewStatsPermissions.ViewPageViewStats))
        {
            return Forbid();
        }

        var date = DateOnly.FromDateTime(day);
        
        var pageViews = await this.sender.Send(new GetPageViewsPerDayQuery(date));

        var contentItems = await this.contentManager.GetAsync(pageViews.Select(x => x.ContentItemId));

        var viewModel = new DayIndexViewModel
        {
            Date = date,
            Items = new List<PageViewsPerContentItem>()
        };

        foreach (var contentItem in contentItems)
        {
            var pageView = pageViews.FirstOrDefault(x => x.ContentItemId == contentItem.ContentItemId);
            if (pageView == null)
            {
                continue;
            }

            var item = new PageViewsPerContentItem
            {
                ContentItemId = contentItem.ContentItemId,
                DisplayText = contentItem.DisplayText,
                Route = contentItem.Get<AutoroutePart>("AutoroutePart"),
                TotalViews = pageView.TotalViews,
                BotViews = pageView.BotViews,
                UniqueVisitors = pageView.UniqueVisitors,
            };

            viewModel.Items.Add(item);
        }
        
        return View(viewModel);
    }
}

Neolution.OrchardCoreModules.PageViewStats/Views/Dashboard/Index.cshtml
@model Neolution.OrchardCoreModules.PageViewStats.ViewModels.DashboardViewModel

@functions
{
    string GetDropDownButtonText()
    {
        return Model.History > 0 ? $"Last {Model.History} days" : "Since ever";
    }
}

<div class="row">
    <div class="col">
        <h1>Page View Statistics</h1>
    </div>
</div>

<ul class="nav nav-tabs">
    <li class="nav-item pr-md-2">
        <a class="nav-link active" id="byday-tab" data-bs-toggle="tab" href="#byday" role="tab" aria-controls="byday" aria-selected="true">@T["By day"]</a>
    </li>
    <li class="nav-item pr-md-2">
        <a class="nav-link" id="bycontentitem-tab" data-bs-toggle="tab" href="#bycontentitem" role="tab" aria-controls="bycontentitem">@T["By content item"]</a>
    </li>
</ul>

<div class="tab-content" id="tabs">

    <div class="tab-pane fade show active" id="byday" role="tabpanel" aria-labelledby="byday-tab">
        <div class="form-group d-inline-flex float-end mb-1">
            <div class="btn-group">
                <div class="dropdown order-md-1">
                    <button type="button" class="btn btn-secondary btn-sm dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                        @GetDropDownButtonText()
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="?history=7#byday">Last week</a></li>
                        <li><a class="dropdown-item" href="?history=14#byday">Last two weeks</a></li>
                        <li><a class="dropdown-item" href="?history=21#byday">Last three weeks</a></li>
                        <li><a class="dropdown-item" href="?history=30#byday">Last month</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <table class="table table-sm table-striped table-hover">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Views</th>
                    <th>Bot Views</th>
                    <th>Unique Visitors</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.PageViewsByDay)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.TotalViews</td>
                        <td>@item.BotViews</td>
                        <td>@item.UniqueVisitors</td>
                        <td><a asp-controller="Day" asp-action="Index" asp-route-day="@item.Id" class="btn btn-success btn-sm">@T["Details"]</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="tab-pane fade" id="bycontentitem" role="tabpanel" aria-labelledby="bycontentitem-tab">
        <div class="form-group d-inline-flex float-end mb-1">
            <div class="btn-group">
                <div class="dropdown order-md-1">
                    <button type="button" class="btn btn-secondary btn-sm dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                        @GetDropDownButtonText()
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="?history=7#bycontentitem">Last week</a></li>
                        <li><a class="dropdown-item" href="?history=14#bycontentitem">Last two weeks</a></li>
                        <li><a class="dropdown-item" href="?history=21#bycontentitem">Last three weeks</a></li>
                        <li><a class="dropdown-item" href="?history=30#bycontentitem">Last month</a></li>
                        <li><a class="dropdown-item" href="?history=0#bycontentitem">Since ever</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <table class="table table-sm table-striped table-hover">
            <thead>
                <tr>
                    <th>ContentItemId</th>
                    <th>Page Title</th>
                    <th>Route</th>
                    <th>Views</th>
                    <th>Bot Views</th>
                    <th>Unique Visitors</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.PageViewsByContentItem)
                {
                    <tr>
                        <td>@item.ContentItemId</td>
                        <td>@item.DisplayText</td>
                        <td>/@item.Route.Path</td>
                        <td>@item.TotalViews</td>
                        <td>@item.BotViews</td>
                        <td>@item.UniqueVisitors</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<script at="Foot">
    $('document').ready(function () {
        let selectedTab = window.location.hash;
        let tabTrigger = new bootstrap.Tab($('.nav-link[href="' + selectedTab + '"]:first'));
        tabTrigger.show();
    });
</script>